server:
  port: 8087

spring:
  application:
    name: report-service

resilience4j:
  circuitbreaker:
    instances:
      customer-service:
        baseConfig: default 
      transaction-service:
        baseConfig: default
  timelimiter:
    instances:
      customer-service:
        baseConfig: default
      transaction-service:
        baseConfig: default
