server:
  port: 8081

spring:
  application:
    name: auth-service
  data:
    mongodb:
      database: userDB
      uri: ${MONGODB_URI:mongodb+srv://bankAdmin:grupo4ntt@bootcamp-bank.2c7fx6u.mongodb.net/bootcamp-bank?retryWrites=true&w=majority&appName=bootcamp-bank}
  kafka:
    consumer:
      group-id: auth-service-group
      properties:
        spring.json.trusted.packages: "com.bootcamp.ntt.auth.dto,com.bootcamp.ntt.customer.dto"

kafka:
  topics:
    user-created: user-created-events
    customer-created: customer-created-events
    transaction-notification: transaction-notification-events

eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    health-check-url-path: /actuator/health
    status-page-url-path: /actuator/info
    instance-id: ${spring.application.name}:${random.value}
    
resilience4j:
  circuitbreaker:
    instances:
      customer-service:
        baseConfig: default 
      transaction-service:
        baseConfig: default
  timelimiter:
    instances:
      customer-service:
        baseConfig: default
      transaction-service:
        baseConfig: default